Padrões do front
fga-desenho-2019-2/qrcomer-front pull request #12
Opened 2019-10-28 20:24 UTC by MatheusBlanco

## Descrição 

Aplicação dos padrões Facade, HOC e Abstract Factory no front-end do projeto, de acordo com os objetivos do seminário 4

## Resolve (Issues)

[#97](https://github.com/fga-desenho-2019-2/Wiki/issues/97)
## PRs relacionados, se houver

branch | PR
------ | ------
outro_pr_relacionado | [link]()

## Tarefas gerais realizadas
* Aplicação do padrão Facade
* Aplicação do padrão HOC
* Aplicação do padrão Abstract Factory

2019-11-04 02:01 UTC, shayanealcantara requested changes
@MatheusBlanco @Phe0 Tentei olhar com cuidado estas mudanças e confesso que é bem difícil porque tem muitos arquivos e não tem uma forma muito eficiente de testar no nosso contexto. Eu vi que vocês trocaram os nomes das rotas e eu achei uma que não foi atualizada em uma das telas. É a `CategorieCard` que se eu entendi direito ainda tá com o path antigo de categoria, como mostra na img. Enfim, seria bom vocês revisarem essas mudanças pequenas porque eu provavelmente deixei passar alguma coisa.
 
![image](https://user-images.githubusercontent.com/33501171/68096119-74818580-fe8d-11e9-81f6-b5c80d1d7397.png)

2019-11-04 18:03 UTC, MatheusBlanco commented
> @MatheusBlanco @Phe0 Tentei olhar com cuidado estas mudanças e confesso que é bem difícil porque tem muitos arquivos e não tem uma forma muito eficiente de testar no nosso contexto. Eu vi que vocês trocaram os nomes das rotas e eu achei uma que não foi atualizada em uma das telas. É a `CategorieCard` que se eu entendi direito ainda tá com o path antigo de categoria, como mostra na img. Enfim, seria bom vocês revisarem essas mudanças pequenas porque eu provavelmente deixei passar alguma coisa.
> 
> ![image](https://user-images.githubusercontent.com/33501171/68096119-74818580-fe8d-11e9-81f6-b5c80d1d7397.png)

@shayanealcantara , o método que chamava a rota com o nome errado não estava sendo utilizada em nenhuma outra situação, portanto foi retirada.

2019-11-05 23:06 UTC, guilhesme23 approved these changes
Como as mudanças sugeridas foram aplicadas, vou aprovar o PR

2019-11-05 23:07 UTC, guilhesme23 approved these changes

2019-11-05 23:08 UTC, merged