Feature/us17 authentication
fga-desenho-2019-2/qrcomer-front pull request #9
Opened 2019-10-19 18:51 UTC by ebmm01

## Descrição 

Adição de criação de usuário, login e logout. Algumas coisas ainda estão meio fora de lugar, mas é justamente para que fique visível como devem ser utilizadas.

## Resolve (Issues)

#85

## Tarefas gerais realizadas
* Adição da store __auth__
* Adição da possibilidade de registrar usuário, login e logout

2019-10-19 18:52 UTC, ebmm01 commented
Ps.: Para testar é necessário rodar o serviço de user na branch feature/84

2019-10-21 22:29 UTC, MatheusBlanco reviewed
Funcionando bem, entretanto é necessário que alguns erros de lint sejam corrigidos, além de resolver os conflitos com a develop

2019-10-21 23:13 UTC, shayanealcantara requested changes
- Não consegui reproduzir o cadastro. Consegui realizar o login com uma conta que criei pela interface do django mesmo. O que é estranho, visto que o Blanco conseguiu, então não sei. Neste link dá pra ver a reprodução da ação que fiz, junto com os logs do erro ao lado. https://drive.google.com/file/d/12L-RDQrTZAJuJu1JEdi62ztO9uwTeU1t/view


- O input do formulário está com uma cor azul. Na tela de edição do perfil do usuário está sendo usada a cor que foi considerada adequada. Está em `/edit-user`

2019-10-21 23:26 UTC, MatheusBlanco commented
Testei novamente a aplicação e é como a Shayane falou. Ele não está mais realizando o cadastro. 

O que é estranho, pois anteriormente, após o cadastro, a aplicação me levou à página que diz: "Página de teste, somente se logado". Minhas informações também foram salvas no banco, sendo que toda vez que tento realizar o login novamente, sou mais uma  vez redirecionado a esta página. Não dei docker-compose down, então as informações do meu cadastro ainda estão lá também.

2019-10-23 00:46 UTC, ebmm01 commented
@shayanealcantara e @MatheusBlanco , todas as alterações e correções foram feitas. Também foi adicionado uma máscara para o cpf e retorno de erro (feedback) em caso de campos inválidos. Lembrando que é estritamente necessário colocar um cpf válido (usar um gerador) e a idade tem que ser >= 18 anos

2019-10-23 04:14 UTC, shayanealcantara reviewed
@ebmm01 Não estou conseguindo realizar o cadastro com erros no campo de CPF. Coloquei um CPF válido como informado. Segue a imagem a seguir.
![oi](https://user-images.githubusercontent.com/33501171/67357412-841ad900-f533-11e9-8858-6ca2a9b81e49.png)

![image](https://user-images.githubusercontent.com/33501171/67357626-39e62780-f534-11e9-8f83-e601e0a81f32.png)

2019-10-23 21:38 UTC, shayanealcantara approved these changes
Consegui fazer a autenticação, show!

2019-10-23 21:39 UTC, merged

2021-10-02 18:23 UTC, 4devs-net-br commented
https://4devs.net.br/gerador-cpf